CRITICAL - 2022-05-13 17:17:57 --> The framework needs the following extension(s) installed and loaded: intl.
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 C:\xampp\htdocs\utsweb3\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#3 C:\xampp\htdocs\utsweb3\spark(45): require('C:\\xampp\\htdocs...')
#4 {main}
ERROR - 2022-05-13 10:23:53 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-05-13 10:23:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\utsweb3\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\utsweb3\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\utsweb3\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('mputra031101@gm...', 'user_email', Array, NULL)
#4 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'mputra031101@gm...', Array, Array)
#5 C:\xampp\htdocs\utsweb3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\utsweb3\app\Controllers\Register.php(28): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Register->save()
#8 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-05-13 10:30:16 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-05-13 10:30:16 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\utsweb3\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\utsweb3\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\utsweb3\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('mputra031101@gm...', 'user_email', Array, NULL)
#4 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'mputra031101@gm...', Array, Array)
#5 C:\xampp\htdocs\utsweb3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\utsweb3\app\Controllers\Register.php(28): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Register->save()
#8 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-05-13 10:30:20 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-05-13 10:30:20 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\utsweb3\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\utsweb3\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\utsweb3\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('mputra031101@gm...', 'user_email', Array, NULL)
#4 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'mputra031101@gm...', Array, Array)
#5 C:\xampp\htdocs\utsweb3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\utsweb3\app\Controllers\Register.php(28): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Register->save()
#8 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-05-13 10:30:28 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-05-13 10:30:28 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\utsweb3\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\utsweb3\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\utsweb3\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('mputra031101@gm...', 'user_email', Array, NULL)
#4 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'mputra031101@gm...', Array, Array)
#5 C:\xampp\htdocs\utsweb3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\utsweb3\app\Controllers\Register.php(28): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Register->save()
#8 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-05-13 10:31:13 --> Error connecting to the database: No connection could be made because the target machine actively refused it
CRITICAL - 2022-05-13 10:31:13 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
#0 C:\xampp\htdocs\utsweb3\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\utsweb3\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\utsweb3\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('mputra031101@gm...', 'user_email', Array, NULL)
#4 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'mputra031101@gm...', Array, Array)
#5 C:\xampp\htdocs\utsweb3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\utsweb3\app\Controllers\Register.php(28): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Register->save()
#8 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-05-13 10:33:01 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-05-13 10:33:01 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\utsweb3\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\utsweb3\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\utsweb3\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('mputra031101@gm...', 'user_email', Array, NULL)
#4 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'mputra031101@gm...', Array, Array)
#5 C:\xampp\htdocs\utsweb3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\utsweb3\app\Controllers\Register.php(28): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Register->save()
#8 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-05-13 10:33:05 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-05-13 10:33:05 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\utsweb3\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\utsweb3\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\utsweb3\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('mputra031101@gm...', 'user_email', Array, NULL)
#4 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'mputra031101@gm...', Array, Array)
#5 C:\xampp\htdocs\utsweb3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\utsweb3\app\Controllers\Register.php(28): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Register->save()
#8 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-05-13 10:33:23 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-05-13 10:33:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\utsweb3\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\utsweb3\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\utsweb3\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('mputra031101@gm...', 'user_email', Array, NULL)
#4 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'mputra031101@gm...', Array, Array)
#5 C:\xampp\htdocs\utsweb3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\utsweb3\app\Controllers\Register.php(28): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Register->save()
#8 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-05-13 10:33:33 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-05-13 10:33:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\utsweb3\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\utsweb3\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\utsweb3\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('mputra031101@gm...', 'user_email', Array, NULL)
#4 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'mputra031101@gm...', Array, Array)
#5 C:\xampp\htdocs\utsweb3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\utsweb3\app\Controllers\Register.php(28): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Register->save()
#8 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-05-13 10:33:43 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-05-13 10:33:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\utsweb3\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\utsweb3\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\utsweb3\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('mputra031101@gm...', 'user_email', Array, NULL)
#4 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'mputra031101@gm...', Array, Array)
#5 C:\xampp\htdocs\utsweb3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\utsweb3\app\Controllers\Register.php(28): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Register->save()
#8 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-05-13 10:36:45 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-13 10:36:45 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\utsweb3\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\utsweb3\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\utsweb3\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('mputra031101@gm...', 'user_email', Array, NULL)
#4 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'mputra031101@gm...', Array, Array)
#5 C:\xampp\htdocs\utsweb3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\utsweb3\app\Controllers\Register.php(28): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Register->save()
#8 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
ERROR - 2022-05-13 10:36:47 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-13 10:36:47 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\utsweb3\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\utsweb3\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 C:\xampp\htdocs\utsweb3\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('mputra031101@gm...', 'user_email', Array, NULL)
#4 C:\xampp\htdocs\utsweb3\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'mputra031101@gm...', Array, Array)
#5 C:\xampp\htdocs\utsweb3\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\utsweb3\app\Controllers\Register.php(28): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Register->save()
#8 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-05-13 10:37:45 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:38:53 --> Class "Config\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:40:57 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:42:03 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:42:04 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:42:05 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:42:05 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:42:10 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:43:03 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:43:04 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:43:05 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:43:17 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:43:17 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:43:18 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:43:18 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:43:18 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:43:18 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:43:19 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:43:19 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:43:19 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:43:19 --> auth filter must have a matching alias defined.
#0 C:\xampp\htdocs\utsweb3\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
#2 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-13 10:44:37 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:45:21 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:45:22 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:45:22 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:45:23 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 10:48:09 --> Class "Config\App\Filters\Auth" not found
#0 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('dashboard', 'before')
#1 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-13 11:32:16 --> Invalid file: dosen_view.php
#0 C:\xampp\htdocs\utsweb3\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('dosen_view.php')
#1 C:\xampp\htdocs\utsweb3\system\Common.php(1089): CodeIgniter\View\View->render('dosen_view', Array, true)
#2 C:\xampp\htdocs\utsweb3\app\Controllers\Dosen.php(12): view('dosen_view', Array)
#3 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Dosen->index()
#4 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dosen))
#5 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-05-13 11:32:40 --> Undefined variable $product
#0 C:\xampp\htdocs\utsweb3\app\Views\dosen_view.php(24): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 24)
#1 C:\xampp\htdocs\utsweb3\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\utsweb3\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\utsweb3\system\Common.php(1089): CodeIgniter\View\View->render('dosen_view', Array, true)
#4 C:\xampp\htdocs\utsweb3\app\Controllers\Dosen.php(12): view('dosen_view', Array)
#5 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(832): App\Controllers\Dosen->index()
#6 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dosen))
#7 C:\xampp\htdocs\utsweb3\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\utsweb3\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\utsweb3\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-05-13 11:33:34 --> Unknown column 'dosen' in 'where clause'
ERROR - 2022-05-13 11:33:40 --> Unknown column 'dosen' in 'where clause'
ERROR - 2022-05-13 11:33:55 --> Unknown column 'dosen' in 'where clause'
ERROR - 2022-05-13 11:34:22 --> Unknown column 'dosen' in 'where clause'
ERROR - 2022-05-13 11:34:29 --> Unknown column 'dosen' in 'where clause'
